from _typeshed import Incomplete
from typing import List

def print_md(md: str): ...

class UserSelect:
    options: List[str]
    title: str
    desc: str
    required: bool
    choices: Incomplete
    def __post_init__(self) -> None: ...
    def single_select(self) -> int: ...
    def multiple_select(self) -> List[int]: ...
    def __init__(self, options, title, desc, required) -> None: ...
