
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-05T17:40:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bea5237de8c54cf66605bba87129f11400a9197b",
 "version": "0.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
