def strr(content:str) -> str|None:...
def intr(content:str) -> int|None:...
def floatr(content:str) -> float|None:...
def boolr(content:str) -> bool|None:...
def listr(content:str) -> list|None:...
def everyr(content:str) -> str|int|float|bool|list|None:...
