# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by: https://openapi-generator.tech
"""

from fireblocks_client.paths.payments_xb_settlements_configs.post import CreateXbSettlementConfig
from fireblocks_client.paths.payments_xb_settlements_flows.post import CreateXbSettlementFlow
from fireblocks_client.paths.payments_xb_settlements_configs_config_id.delete import DeleteXbSettlementConfig
from fireblocks_client.paths.payments_xb_settlements_flows_flow_id_actions_execute.post import ExecuteXbSettlementFlowAction
from fireblocks_client.paths.payments_xb_settlements_configs_config_id.get import GetXbSettlementConfigById
from fireblocks_client.paths.payments_xb_settlements_configs.get import GetXbSettlementConfigs
from fireblocks_client.paths.payments_xb_settlements_flows_flow_id.get import GetXbSettlementFlowById
from fireblocks_client.paths.payments_xb_settlements_configs_config_id.put import UpdateXbSettlementConfig


class PaymentsCrossBorderSettlementApi(
    CreateXbSettlementConfig,
    CreateXbSettlementFlow,
    DeleteXbSettlementConfig,
    ExecuteXbSettlementFlowAction,
    GetXbSettlementConfigById,
    GetXbSettlementConfigs,
    GetXbSettlementFlowById,
    UpdateXbSettlementConfig,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
