# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by: https://openapi-generator.tech
"""

from fireblocks_client.paths.transactions_tx_id_cancel.post import CancelTransaction
from fireblocks_client.paths.transactions.post import CreateTransaction
from fireblocks_client.paths.transactions_tx_id_drop.post import DropTransaction
from fireblocks_client.paths.estimate_network_fee.get import EstimateNetworkFee
from fireblocks_client.paths.transactions_estimate_fee.post import EstimateTransactionFee
from fireblocks_client.paths.transactions_tx_id_freeze.post import FreezeTransaction
from fireblocks_client.paths.transactions_external_tx_id_external_tx_id_.get import GetTransactionByExternalId
from fireblocks_client.paths.transactions_tx_id.get import GetTransactionById
from fireblocks_client.paths.transactions.get import GetTransactions
from fireblocks_client.paths.transactions_tx_id_set_confirmation_threshold.post import SetConfirmationThresholdForTransaction
from fireblocks_client.paths.tx_hash_tx_hash_set_confirmation_threshold.post import SetConfirmationThresholdForTransactionByHash
from fireblocks_client.paths.transactions_tx_id_unfreeze.post import UnfreezeTransaction
from fireblocks_client.paths.transactions_validate_address_asset_id_address.get import ValidateAddress


class TransactionsApi(
    CancelTransaction,
    CreateTransaction,
    DropTransaction,
    EstimateNetworkFee,
    EstimateTransactionFee,
    FreezeTransaction,
    GetTransactionByExternalId,
    GetTransactionById,
    GetTransactions,
    SetConfirmationThresholdForTransaction,
    SetConfirmationThresholdForTransactionByHash,
    UnfreezeTransaction,
    ValidateAddress,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
