# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by: https://openapi-generator.tech
"""

from fireblocks_client.paths.screening_travel_rule_vasp_did.get import GetVaspbyDid
from fireblocks_client.paths.screening_travel_rule_vasp.get import GetVasps
from fireblocks_client.paths.screeening_travel_rule_vasp_update.put import TravelRuleApiControllerUpdateVasp
from fireblocks_client.paths.screening_travel_rule_transaction_validate_full.post import ValidateFullTravelRuleTransaction
from fireblocks_client.paths.screening_travel_rule_transaction_validate.post import ValidateTravelRuleTransaction


class TravelRuleBetaApi(
    GetVaspbyDid,
    GetVasps,
    TravelRuleApiControllerUpdateVasp,
    ValidateFullTravelRuleTransaction,
    ValidateTravelRuleTransaction,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
