
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-05T01:04:21-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "99ccc2286f2e23ece519e5059ba6358df81656a0",
 "version": "0.31.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
