from _typeshed import Incomplete
from amsdal_framework.authentication.handlers.base import BASE_AUTH_URL as BASE_AUTH_URL
from amsdal_framework.configs.main import settings as settings
from amsdal_framework.errors import AmsdalAuthenticationError as AmsdalAuthenticationError

LICENCE_PATH: Incomplete
LICENCE_MESSAGE: Incomplete

def _input(msg: str) -> str: ...
def _print(msg: str) -> None: ...
def want_signup_input() -> str: ...
def licence_input() -> str: ...
def organization_name_input() -> str: ...
def email_input() -> str: ...

class SignupService:
    @classmethod
    def signup_prompt(cls) -> bool: ...
