VERSION_YEAR = 2023
VERSION_MONTH = int('12')
VERSION_DAY = int('04')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('47')
MAJOR_VERSION = 0
MINOR_VERSION = 2
PATCH_VERSION = 202312042047
version_date = '2023/12/04 20:47'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
