
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-01T18:39:34+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "88fa1246cfd1b7d00de2d2ba73558fcc31443fbb",
 "version": "0.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
