# This file was auto-generated by Fern from our API Definition.

import typing
import urllib.parse
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.jsonable_encoder import jsonable_encoder
from ...core.remove_none_from_dict import remove_none_from_dict
from ..embed.types.embed_request_truncate import EmbedRequestTruncate
from ..embed.types.embed_response import EmbedResponse

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SagemakerClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def embed(
        self,
        endpoint_name: str,
        *,
        texts: typing.List[str],
        model: typing.Optional[str] = OMIT,
        input_type: typing.Optional[str] = OMIT,
        truncate: typing.Optional[EmbedRequestTruncate] = OMIT,
        variant: typing.Optional[str] = None,
    ) -> EmbedResponse:
        """
        Parameters:
            - endpoint_name: str.

            - texts: typing.List[str].

            - model: typing.Optional[str].

            - input_type: typing.Optional[str].

            - truncate: typing.Optional[EmbedRequestTruncate].

            - variant: typing.Optional[str].
        """
        _request: typing.Dict[str, typing.Any] = {"texts": texts}
        if model is not OMIT:
            _request["model"] = model
        if input_type is not OMIT:
            _request["input_type"] = input_type
        if truncate is not OMIT:
            _request["truncate"] = truncate
        _response = self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(
                f"{self._client_wrapper.get_environment().sagemaker}/", f"model/{endpoint_name}/invoke"
            ),
            json=jsonable_encoder(_request),
            headers=remove_none_from_dict(
                {**self._client_wrapper.get_headers(), "X-Amzn-SageMaker-Target-Variant": variant}
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(EmbedResponse, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncSagemakerClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def embed(
        self,
        endpoint_name: str,
        *,
        texts: typing.List[str],
        model: typing.Optional[str] = OMIT,
        input_type: typing.Optional[str] = OMIT,
        truncate: typing.Optional[EmbedRequestTruncate] = OMIT,
        variant: typing.Optional[str] = None,
    ) -> EmbedResponse:
        """
        Parameters:
            - endpoint_name: str.

            - texts: typing.List[str].

            - model: typing.Optional[str].

            - input_type: typing.Optional[str].

            - truncate: typing.Optional[EmbedRequestTruncate].

            - variant: typing.Optional[str].
        """
        _request: typing.Dict[str, typing.Any] = {"texts": texts}
        if model is not OMIT:
            _request["model"] = model
        if input_type is not OMIT:
            _request["input_type"] = input_type
        if truncate is not OMIT:
            _request["truncate"] = truncate
        _response = await self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(
                f"{self._client_wrapper.get_environment().sagemaker}/", f"model/{endpoint_name}/invoke"
            ),
            json=jsonable_encoder(_request),
            headers=remove_none_from_dict(
                {**self._client_wrapper.get_headers(), "X-Amzn-SageMaker-Target-Variant": variant}
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(EmbedResponse, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
