
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-05T18:05:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3be2f32b2692e5375b8756f9ac40e15ac1a71dfa",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
