from .container import uSwidContainer as uSwidContainer
from typing import Optional

class uSwidFormatBase:
    def __init__(self) -> None: ...
    def load(self, blob: bytes, path: Optional[str] = ...) -> uSwidContainer: ...
    def save(self, container: uSwidContainer) -> bytes: ...
