
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-04T18:53:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bef8079786744e342c9166a2f675f331c6027a1f",
 "version": "3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
