# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import fireblocks_client
from fireblocks_client.model.media_entity_response import MediaEntityResponse
from fireblocks_client import configuration


class TestMediaEntityResponse(unittest.TestCase):
    """MediaEntityResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
