from django.db import models

class ColumnVisibility(models.Model):
    id = models.IntegerField(primary_key=True)
    created_at = models.DateTimeField()
    updated_by = models.IntegerField()
    updated_at = models.DateTimeField()
    organization = models.ForeignKey('Organization', models.DO_NOTHING)
    user_id = models.IntegerField()
    processed_date = models.BooleanField()
    request_date = models.BooleanField()
    make = models.BooleanField()
    model = models.BooleanField()
    model_number = models.BooleanField()
    memory_size = models.BooleanField()
    unique_id = models.BooleanField()
    imei = models.BooleanField()
    meid = models.BooleanField()
    serial_number = models.BooleanField()
    tracking_number = models.BooleanField()
    grade = models.BooleanField()
    condition_notes = models.BooleanField()
    fmi = models.BooleanField()
    value = models.BooleanField()
    battery_ratio = models.BooleanField()
    tracking_reference = models.BooleanField()
    reference = models.BooleanField()
    lock_status = models.BooleanField()
    po = models.BooleanField()
    battery = models.BooleanField()
    glass_description = models.BooleanField()
    lcd_description = models.BooleanField()
    housing_description = models.BooleanField()
    corner_description = models.BooleanField()
    first_name = models.BooleanField()
    last_name = models.BooleanField()
    city = models.BooleanField()
    state = models.BooleanField()
    phone = models.BooleanField()
    email = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'column_visibility'
