# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CommandModel(str, enum.Enum):
    COMMAND = "cohere.command-text-v14"
    COMMAND_LIGHT = "cohere.command-light-text-v14"

    def visit(self, command: typing.Callable[[], T_Result], command_light: typing.Callable[[], T_Result]) -> T_Result:
        if self is CommandModel.COMMAND:
            return command()
        if self is CommandModel.COMMAND_LIGHT:
            return command_light()
