# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by: https://openapi-generator.tech
"""

from fireblocks_client.paths.off_exchange_add.post import AddOffExchange
from fireblocks_client.paths.off_exchange_collateral_accounts_main_exchange_account_id.get import GetOffExchangeCollateralAccounts
from fireblocks_client.paths.off_exchange_settlements_transactions.get import GetOffExchangeSettlementTransactions
from fireblocks_client.paths.off_exchange_remove.post import RemoveOffExchange
from fireblocks_client.paths.off_exchange_settlements_trader.post import SettleOffExchangeTrades


class OffExchangesApi(
    AddOffExchange,
    GetOffExchangeCollateralAccounts,
    GetOffExchangeSettlementTransactions,
    RemoveOffExchange,
    SettleOffExchangeTrades,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
