# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by: https://openapi-generator.tech
"""

from fireblocks_client.paths.tap_active_policy.get import GetActivePolicy
from fireblocks_client.paths.tap_draft.get import GetDraft
from fireblocks_client.paths.tap_draft.post import PublishDraft
from fireblocks_client.paths.tap_publish.post import PublishPolicyRules
from fireblocks_client.paths.tap_draft.put import UpdateDraft


class PolicyEditorBetaApi(
    GetActivePolicy,
    GetDraft,
    PublishDraft,
    PublishPolicyRules,
    UpdateDraft,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
