# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class EmbedRequestTruncate(str, enum.Enum):
    NONE = "NONE"
    START = "START"
    END = "END"

    def visit(
        self,
        none: typing.Callable[[], T_Result],
        start: typing.Callable[[], T_Result],
        end: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EmbedRequestTruncate.NONE:
            return none()
        if self is EmbedRequestTruncate.START:
            return start()
        if self is EmbedRequestTruncate.END:
            return end()
