
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-23T14:59:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d488a32477b8421fa8dc7037ae40a4415ccdb08",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
