
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-05T03:36:19-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b04b4ed9683ae7d6994e79613c09fcb9d7803df6",
 "version": "5.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
